name: tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: install dependencies
      run: sudo apt-get install libc-ares-dev libpcre2-dev
    - name: reconf
      run: autoreconf -i
    - name: configure
      run: ./configure --enable-tests
    - name: make
      run: make -j$(nproc)
    - name: make check
      run: make -j$(nproc) check
